### PR TITLE
fix typo Avalanche

### PR DESCRIPTION
**Pull request by pcaversaccio**
Not my biggest contribution but just wanted to quickly fix this typo ;-)

### CODE REVIEW

**Comment by pcaversaccio** [comment]
Since nobody wants to merge this small fix, I will close this soon.

**Review by dekz — APPROVED** [review]

**Comment by pcaversaccio** [comment]
@dekz can you please merge?

**Comment by johnrjj** [comment]
@dekz plz merge

**Comment by johnrjj** [comment]
ty for the contribution!

**Pull request merged**
