### PR TITLE
add eip 1271 support to v4

### PR DESCRIPTION
**Pull request by arilotter**

### CODE REVIEW

**Comment by arilotter** [comment]
I believe this does similar work to [`aa0edea` (#70)](https://github.com/trader-xyz/nft-swap-sdk/pull/70/commits/aa0edeabf7372109466c43f7e24131dd531af30e) , so they may want to be combined.

**Comment by johnrjj** [comment]
Thanks, Ari! Will release this today

**Comment by johnrjj** [comment]
Just doing some quick testing and will cut a new version :)

**Comment by johnrjj** [comment]
Released in 0.31

https://github.com/trader-xyz/nft-swap-sdk/releases/tag/v0.31.0

**Pull request merged**
